repository_type: pipeline

nf_core_version: 3.1.2

lint:
  files_unchanged:
  - .github/CONTRIBUTING.md
  - assets/sendmail_template.txt
  - .prettierignore
  - .prettierignore
  - .prettierignore
  - .github/CONTRIBUTING.md
  - assets/sendmail_template.txt
  - .prettierignore
  - .prettierignore
  - .prettierignore
  - CODE_OF_CONDUCT.md
  - assets/nf-core-nallo-refs_logo_light.png
  - docs/images/nf-core-nallo-refs_logo_light.png
  - docs/images/nf-core-nallo-refs_logo_dark.png
  - .github/ISSUE_TEMPLATE/bug_report.yml
  - .github/CONTRIBUTING.md
  - .github/PULL_REQUEST_TEMPLATE.md
  - assets/email_template.txt
  - docs/README.md
  nextflow_config:
  - manifest.name
  - manifest.homePage
  - validation.help.beforeText
  - validation.help.afterText
  - validation.summary.beforeText
  - validation.summary.afterText
  multiqc_config: false
  files_exist:
  - conf/igenomes.config
  - conf/igenomes_ignored.config
  - CITATIONS.md
  - assets/multiqc_config.yml
  - assets/email_template.html
  - assets/sendmail_template.txt
  - assets/email_template.txt
  - conf/igenomes.config
  - conf/igenomes_ignored.config
  - CITATIONS.md
  - assets/multiqc_config.yml
  - assets/email_template.html
  - assets/sendmail_template.txt
  - assets/email_template.txt
  - CODE_OF_CONDUCT.md
  - assets/nf-core-nallo-refs_logo_light.png
  - docs/images/nf-core-nallo-refs_logo_light.png
  - docs/images/nf-core-nallo-refs_logo_dark.png
  - .github/ISSUE_TEMPLATE/config.yml
  - .github/workflows/awstest.yml
  - .github/workflows/awsfulltest.yml

template:
  org: genomic-medicine-sweden
  name: nallo-refs
  description: A Nexflow pipeline to download and create genomic-medicine-sweden/nallo
    references
  author: Felix Lenner
  version: 0.3.0dev
  force: true
  outdir: .
  skip_features:
  - igenomes
  - citations
  - multiqc
  - fastqc
  - email
  - adaptivecard
  - slackreport
  is_nfcore: false
